### ISSUE TITLE
Task to get reset password link.

### ISSUE THREAD

**Issue by nh758** [digi-serve/ab_service_process_manager#9]
## Requirements
1. Generate a url to reset a password for a given user.
2. Later process steps can use the url

### Tasks
- [ ] Write Documentation

## Reference
Related to digi-serve/ab_platform_web#51
o ->[ Task: Get Url ]  -> [Task: Send email with url ] -> **o**

**Comment by Achoobert** [comment]
I would _really_ like to see this be a bit more agnostic, rather than necessarily being password reset specific. 

Send user email: has link for them to go to a page.
The page can be customized with the form widget


I would use this feature to request things like missing receipt images, request payment confirmation, or to get critical missing HR fields.

I'm not sure how to avoid it looking like a fishing email though.

**Comment by nh758** [comment]
Just to be clear this task does not include sending emails. We will use the email task for that. The goal is to get a url with a token that can be used later in the process.

@guyyoo This is where Johnny gets the user token for the reset password, I'm not user if we can use the same handler: `https://github.com/digi-serve/ab_service_user_manager/blob/develop/handlers/user-for-token.js`
